#!/bin/bash
# shellcheck source=./.xgitconfig
. "$(pwd)/.xgitconfig"

function branch() {
  name=${3// /_}
  branch_name="$slug$project-$2_$name"
  git checkout -b "$branch_name"
}

function commit() {
  branch_name=$(git symbolic-ref -q HEAD)
  branch_name=${branch_name##refs/heads/}
  branch_name=${branch_name:-HEAD}
  jira_id=$(expr "$branch_name" : "[a-z]*/\($project-[0-9][0-9][0-9]\)")
  git commit -a -m "$jira_id $2"
}

function checkout() {
  branch=$(git branch --all | grep -i -m1 $2 | xargs)
  git checkout "$branch"
}

case "$1" in
  "branch")
    branch "$@"
    ;;
  "b")
    branch "$@"
    ;;
  "commit")
    commit "$@"
    ;;
  "c")
    commit "$@"
    ;;
  "checkout")
    checkout "$@"
    ;;
  "x")
    checkout "$@"
    ;;

  *) printf "
XGit CLI:\n
Available commands:
  1: [b/branch] - create branch
  2: [c/commit] - create a commit
  3: [x/checkout] - checkout a branch
  \nFor more help, see the readme at: https://github.com/cameronolivier/git_flow_helpers
  \n"
esac
